$ARCHIVE_NAME = "Robco Auto Sort - Main.ba2"

$BUILD_PATH = "$PSScriptRoot\build"
$BUILD_PATH_DEBUG = "$BUILD_PATH\debug"
$BUILD_PATH_RELEASE = "$BUILD_PATH\release"

$MESHES_PATH = "$PSScriptRoot\meshes"

$OUTPUT_PATH = "$PSScriptRoot\FOMOD\filesets\base"
$OUTPUT_PATH_DEBUG = "$OUTPUT_PATH\debug\Data"
$OUTPUT_PATH_RELEASE = "$OUTPUT_PATH\release\Data"

$FOLDERS_DEBUG = "$BUILD_PATH_DEBUG,$MESHES_PATH"
$FOLDERS_RELEASE = "$BUILD_PATH_RELEASE,$MESHES_PATH"

$FILEPATH_DEBUG = "$OUTPUT_PATH_DEBUG\$ARCHIVE_NAME"
$FILEPATH_RELEASE= "$OUTPUT_PATH_RELEASE\$ARCHIVE_NAME"

Archive2 "$FOLDERS_DEBUG" -create="$FILEPATH_DEBUG"
Archive2 "$FOLDERS_RELEASE" -create="$FILEPATH_RELEASE"

Copy-Item -Path "$FILEPATH_DEBUG" -DESTINATION "$env:FALLOUT4_PATH\Data" -RECURSE -FORCE